package model

type SongInfoMergeTmp struct {
	SourceId              int
	Source                int
	WordPart              int
	LrcChannel            int
	LrcSize2              int
	Gender                int
	Lang                  int
	Year                  int
	IsDuet                int
	SongSize              int
	LrcSize               int
	IconSize              int
	SongTime              int
	Status                int
	LrcType               int
	YouTubeSongType       int
	Intonation            int
	MvSize                int
	BackgroundImageSize   string
	DossierName           string
	UpdateTime            string
	CreateDate            string
	SongPath              string
	SongNameStrokeNum     string
	SingerStrokeNum       string
	SongNameSimple        string
	SingerSimple          string
	SongVersion           string
	LrcVersion            string
	SongChinesePhonetic   string
	SingerChinesePhonetic string
	SearchWord            string
	SongName              string
	SongNamePhonetic      string
	Singer                string
	SingerNamePhonetic    string
	Album                 string
	LineWriter            string
	SongWrite             string
}
